// 1. Diccionario de traducciones
const textos = {
    'ES': {
        // mapa
        'destinos': 'Destinos',
        'comunidad': 'Comunidad',
        'otros_rincones': 'Otros rincones',
        'descubre_aventura': 'Descubre tu próxima aventura.',
        'destinos_increibles': 'Explora destinos increibles y crea recuerdos inolvidables',
        'explorar_destinos': 'Explorar Destinos.',
        'destinos_destacados': 'Destinos destacados.',
        'francia': 'París, Francia',
        'japon': 'Tokyo, Japón',
        'peru': 'Machu Picchu, Perú.',
        'ver_mas': 'Ver más',
        'dicen_viajeros': 'Lo que dicen nuestros viajeros',
        'mensaje_joselito1': '¡La mejor experiencia de mi vida!',
        'ir_comunidad': 'Ir a la comunidad',
        'newsletter': 'Suscríbete a nuestra newsletter.',
        'recibe_info': 'Recibe información sobre tus próximas grandes aventuras',
        'suscribir': 'Suscríbete',
        'sobre_nosotros': 'Sobre nosotros',
        'politica_privacidad': 'Política de Privacidad',
        'ayuda': 'Ayuda',
        // otros rincones
        'seleccion_contiente':'Selecciona Contienente',
        'todos_contientes':'Todos los Contienetes',
        'europa':'EUROPA',
        'asia':'ASIA',
        'africa':'ÁFRICA',
        'america_n':'AMÉRICA DEL NORTE',
        'america_s':'AMÉRICA DEL SUR',
        'oceania':'OCEANÍA',
        'seleccion_pais':'Selecciona País',
        'todos_paises':'Todos los Paises',
        'bucador_destinos':'Buscar Destinos',
        'viena':'Viena, Austria',
        'viena1':'Ciudad imperial con museos y música clásica a cada paso. El Palacio de Schönbrunn y la Ringstrasse condensan el barroco y el historicismo, mientras cafés como Demel mantienen la tradición pastelera. Ideal para caminar entre parques y teatros de ópera.',
        'brujas':'Brujas, Bélgica',
        'brujas1':'Centro medieval perfectamente conservado, canales bordeados de árboles y plazas adoquinadas como el Markt. Campanarios, casas gremiales y chocolaterías crean un ambiente de cuento que invita a perderse sin prisa.',
        'copenhague':'Copenhague, Dinamarca',
        'copenhague1':'Equilibrio entre diseño contemporáneo y tradición nórdica. Nyhavn, Tívoli y barrios ciclistas muestran una ciudad humana y acogedora; gastronomía de vanguardia y respeto por el espacio público.',
        'luibliana':'Luibliana, Eslovenia',
        'luibliana1':'Capital pequeña y escénica, con casco peatonal, cafés junto al río y el castillo en lo alto. Base ideal para excursiones al lago Bled y los Alpes Julianos.',
        'barcelona':'Barcelona, España',
        'barcelona1':'Modernismo de Gaudí, mar y montaña en un mismo plano. La Sagrada Familia, Park Güell y la vida de barrio conviven con mercados y museos; paseos desde Montjuïc a las playas.',
        'sevilla':'Sevilla, España',
        'sevilla1':'Casco histórico monumental, patios y azulejos. El Alcázar, la Catedral y el barrio de Santa Cruz se suman a una potente cultura de tapas y al flamenco.',
        'tallin':'Tallin, Estonia',
        'tallin1':'Ciudad vieja medieval amurallada, torres y tejados de colores con vistas al Báltico. Invierno frío, pero fotogénico desde Toompea.',
        'paris':'París, Francia',
        'paris1':'Romance urbano: Sena, bulevares y museos icónicos. Barrios con identidad propia y cafés a pie de calle; Notre Dame, Sacré-Coeur y la Torre Eiffel como hitos imprescindibles.',
        'budapest':'Budapest, Hungría',
        'budapest1':'Arquitectura Art Nouveau, baños termales y paseos nocturnos sobre el Danubio. El Parlamento brilla al caer la tarde desde el Puente de las Cadenas.',
        'florencia':'Florencia, Italia',
        'florencia1':'Cuna del Renacimiento: Duomo, Uffizi y artesanías en el Oltrarno. Una ciudad-museo viva donde cada calle guarda esculturas, palacios y talleres.',
        'roma':'Roma, Italia',
        'roma1':'La “Ciudad Eterna” combina ruinas clásicas, plazas barrocas y vida de barrio. Del Panteón a la Fontana di Trevi, la historia convive con trattorias y terrazas.',
        'venecia':'Venecia, Italia',
        'venecia1':'Sin coches y con un trazado acuático único. Canales, palacios y puentes conectan islas; desde San Marcos a los barrios más tranquilos, es pura contemplación.',
        'valeta':'La Valeta, Malta',
        'valeta1':'Fortificada y barroca, con miradores al Gran Puerto. Palacios, iglesias y museos concentrados en un casco compacto y caminable.',
        'bergen':'Bergen, Noruega',
        'bergen1':'Casas de madera en Bryggen, puerto vivo y montañas que caen a fiordos. Punto de partida perfecto para rutas escénicas.',
        'amsterdam':'Ámsterdam, Paises Bajos',
        'amsterdam1':'Canales Patrimonio de la UNESCO, gables estrechos y cultura ciclista. Museos de primer nivel y barrios verdes conectados por puentes.',
        'oporto':'Oporto, Portugal',
        'oporto1':'Azulejos, puentes sobre el Duero y bodegas de vino de Oporto. Librería Lello y piscinas de Leça como iconos contemporáneos.',
        'londres':'Londres, Reino Unido',
        'londres1':'Historia y vanguardia a orillas del Támesis. Museos gratuitos, parques inmensos y una escena cultural y gastronómica inagotable.',
        'edimburgo':'Edimburgo, Reino Unido',
        'edimburgo1':'Royal Mile, castillo y colinas verdes. La roca volcánica de Arthur’s Seat regala una panorámica excepcional sobre la ciudad de piedra.',
        'praga':'Prga, República Checa',
        'praga1':'Cúpulas y torres góticas sobre un casco antiguo fotogénico. Puente de Carlos al amanecer y cafés históricos con música y literatura.',
        'lucerna':'Lucerna, Suiza',
        'lucerna1':'Lago, montes cercanos y el Kapellbrücke como postal. Tejados medievales y aire alpino a pocos minutos de rutas de montaña.',
        'zurich':'Zurich, Suiza',
        'zurich1':'Casco antiguo elegante junto al lago, museos, galerías y vida junto al agua. Veranos vibrantes y eficiencia suiza en cada detalle.',
        'reikiavik':'Reikiavik, Islandia',
        'reikiavik1':'Arquitectura moderna como Harpa y Hallgrímskirkja entre paisajes volcánicos. Base para auroras y baños termales cercanos.',
        'beijing':'Beijing, China',
        'beijing1':'Capital imperial con la Ciudad Prohibida, hutongs y avenidas amplias. Puerta a tramos cercanos de la Gran Muralla y a una cocina regional riquísima.',
        'hong':'Hong Kong, China',
        'hong1':'Horizonte denso en torno a un puerto lleno de ferris. Montañas, islas y reservas naturales a minutos del centro financiero.',
        'seul':'Seúl, Corea del Sur',
        'seul1':'Rascacielos y palacios, mercados nocturnos y una red de metro impecable. Distritos como Bukchon y Myeongdong muestran tradición y moda.',
        'jaipur':'Jaipur, India',
        'jaipur1':'La “Ciudad Rosa”: Hawa Mahal, fuertes y bazares color salmón. Artesanías, joyería y gastronomía del Rajastán en palacios y calles.',
        'kioto':'Kioto, Japón',
        'kioto1':'Templos, santuarios y jardines clásicos. Hanami en primavera, rutas arboladas y posibilidad de cruzarse con geishas en Gion.',
        'luang':'Luang Prabang, Laos',
        'luang1':'Patrimonio UNESCO junto a la confluencia de ríos. Procesiones de monjes al amanecer, cascadas cercanas y arquitectura colonial-budista.',
        'beirut':'Beirut, Líbano',
        'beirut1':'Playas, clubes y azoteas frente a mezquitas y zocos históricos. Gastronomía y vida nocturna con aire mediterráneo y levantino.',
        'mascate':'Mascate, Omán',
        'mascate1':'Bahías y montañas enmarcando mezquitas, zocos y fuertes portugueses. Paseos costeros y arquitectura blanca junto al Golfo de Omán.',
        'doha':'Doha, Qatar',
        'doha1':'Corniche con skyline futurista, Souq Waqif y el Museo de Arte Islámico de I. M. Pei. Mezcla de tradición y nuevas áreas culturales.',
        'mai':'Chiang Mai, Tailandia',
        'mai1':'Templos en la ladera, cafés y mercados creativos. Punto de partida para naturaleza del norte y experiencias culinarias intensas.',
        'hanoi':'Hanoi, Vietman',
        'hanoi1':'Lagos, templos y barrio francés con aire romántico. Calles angostas con cafés tradicionales y mercados vibrantes.',
        'singapur':'Singapur, Singapur',
        'singapur1':'Ciudad-jardín con selva urbana, Jardín Botánico y Gardens by the Bay. Templos, casas patrimoniales y una logística impecable para moverse.',
        'chef':'Chefchaouen, Marruecos',
        'chef1':'Medina azul entre montañas del Rif. Callejuelas pintadas, puertas artesanales y miradores cercanos para ver el conjunto desde arriba.',
        'cabo':'Ciudad del Cabo, Sudáfrica',
        'cabo1':'Table Mountain, playas con pingüinos y barrios coloridos como Bo-Kaap. Jardines, viñedos cercanos y rutas panorámicas costeras.',
        'sidney':'Sídney, Australia',
        'sidney1':'Ópera icónica, bahía navegable y playas urbanas como Bondi. Ferris cotidianos y parques frente al agua.',
        'queen':'Queenstown, Nueva Zelanda',
        'queen1':'Capital de la adrenalina entre lago y montañas. Miradores naturales, aventuras y paisajes cinematográficos.',
        'quebec':'Ciudad de Quebec, Canadá',
        'quebec1':'Casco amurallado en altura con vistas al San Lorenzo. Ambiente europeo, tejados empinados y puestas de sol rosadas.',
        'ny':'Nueva York, Estados Unidos',
        'ny1':'Arquitectura icónica, parques como Central Park y una escena artística incomparable. Energía urbana que no se apaga.',
        'sf':'San Francisco, Estados Unidos',
        'sf1':'Puente Golden Gate, colinas y casas victorianas. Museos de talla mundial y barrios con carácter propio.',
        'sm':'an Miguel de Allende, México',
        'sm1':'Centro colonial con parroquia neogótica rosada. Calles adoquinadas, patios y arte en galerías y talleres.',
        'ba':'Buenos Aires, Argentina',
        'ba1':'Barrios con identidad (Recoleta, San Telmo, La Boca), arquitectura variada y vida cultural intensa. Tango, parrillas y librerías en edificios emblemáticos.',
        'rio':'Rio de Janeiro, Brasil',
        'rio1':'layas míticas, selva urbana y el Cristo Redentor vigilando bahías y morros. Ritmo de samba en calles y plazas.',
        'cartagena':'Cartagena, Colombia',
        'cartagena1':'Murallas, plazas y casonas coloniales cubiertas de buganvillas. Getsemaní y Bocagrande muestran su cara creativa y moderna.',
        'quito':'Quito, Ecuador',
        'quito1':'Casco histórico dorado bajo volcanes andinos. Vistas desde la Basílica del Voto Nacional y mercados tradicionales.',
        'cuzco':'Cuzco, Perú',
        'cuzco1':'Antigua capital inca con plazas, conventos y calles empedradas. Punto de partida a Machu Picchu y miradores como el Cristo Blanco.',
        // compra (páginas individuales)
        'titulo_brasil': 'Ritmo y Naturaleza por Brasil',
        'titulo_japon': 'Japón, Tradición y Modernidad',
        'titulo_francia': 'Arte por las Calles Francesas',
        'titulo_noruega': 'Paisajes de Ensueño en Noruega',
        'titulo_italia': 'Descubre la Belleza de Italia',
        'titulo_marruecos': 'Colores y Aromas de Marruecos',

        'descripcion_brasil': 'Vive la energía de Río, explora la selva amazónica y relájate en sus playas tropicales',
        'descripcion_japon': 'Sumérgete en la cultura japonesa y descubre sus tradiciones milenarias',
        'descripcion_noruega': 'Atrévete a explorar la magia de los fiordos y la fascinante historia escandinava',
        'descripcion_francia': 'Recorre París, la Provenza y la Riviera francesa entre arte, cultura y sabores inolvidables',
        'descripcion_italia': 'Descubre la belleza de Italia a través de sus paisajes, cultura y gastronomía',
        'descripcion_marruecos': 'Déjate llevar por los sentidos en un viaje inolvidable a través del mundo bereber',
        'descripcion_pack': 'Descripción del pack:',

        'texto_pack_brasil': 'Un recorrido por lo mejor de Brasil: Río de Janeiro y sus playas, la increíble biodiversidad del Amazonas, y la cultura vibrante del país con música, baile y gastronomía. Ideal para quienes buscan mezcla de naturaleza y fiesta.',
        'texto_pack_japon': 'Sumérgete en la cultura japonesa y descubre sus tradiciones milenarias: comtempla la majestuosidad del Monte Fuji, explora los templos ancestrales de Kioto y disfruta de la vibrante vida urbana de Tokio. Este viaje de 11 días tellevará a través de una mezcla fascinante de historia, tecnología y naturaleza, ofreciéndote una experiencia inolvidable en el corazón de Japón. ',
        'texto_pack_noruega': 'Atrévete a explorar la magia de los majestuosos fiordos noruegos, descubre la fascinante historia vikinga y sumérgete en paisajes naturales que parecen sacados de un sueño. Este viaje combina aventura, cultura escandinava y la tranquilidad del norte, ofreciendo una experiencia inolvidable para quienes buscan conectar con la naturaleza y la historia de una región única en el mundo.',
        'texto_pack_francia': 'Descubre la riqueza cultural de Francia: pasea por las calles de París, visita museos emblemáticos como el Louvre, disfruta de la cocina francesa en mercados locales y explora la belleza de la Provenza y la Costa Azul. Un viaje pensado para amantes del arte, la historia y la gastronomía.',
        'texto_pack_italia': ' Recorre ciudades históricas como Roma y Florencia, disfruta de la auténtica pasta, pizza y vinos locales, y sumérgete en tradiciones y monumentos que hacen de Italia un país único. Este viaje combina aventura, historia y placer culinario en una experiencia inolvidable para quienes quieren explorar lo mejor del país de forma auténtica.',
        'texto_pack_marruecos': ' Déjate llevar por los sentidos en un viaje inolvidable a tráves de mundo bereber: explora los paisajes desérticos y las montañas del Atlas, descubre la hospitalidad de sus pueblos, sus colores, aromas y tradiciones ancestrales. Una experiencia que combina aventura, cultura y autenticidad en cada rincón de Marruecos. ',
        'info_personal': 'Información personal',
        'nombre_completo': 'Nombre completo:',
        'correo': 'Correo electrónico',
        'ciudad': 'Ciudad',
        'c_postal': 'Código postal:',
        'telefono_contacto': 'Teléfono de contacto:',
        'siguiente': 'Siguiente',
        'borrar': 'Borrar',
        // pago
        'formulario_compra': 'Formulario de compra',
        'tipo_tarjeta': 'Tipo de tarjeta:',
        'seleccion_opcion': 'Seleccione una opción',
        'num_tarjeta': 'Número de tarjeta:',
        'titular_tarjeta': 'Titular de la tarjeta',
        'fecha_caducidad': 'Fecha de caducidad',
        'codigo_cvv': 'Código CVV:',
        'volver': 'Volver',
        // ampliación del pago
        'revisar':'Revisa tus datos y completa la ampliación',
        'revisar2':'Verifica los datos del paso anterior y añade la información adicional necesaria.',
        'info_adicional':'Información adicional',
        'acompanante':'Acompañantes:',
        'mascotas':'Viajo con mascotas:',
        'si':'Sí',
        'alergias': 'Intolerancias / Alergias:',
        'coment_adicional': 'Comentarios adicionales',
        'condiciones1': 'Acepto los',
        'condiciones2': 'términos y condiciones',
        'condiciones3': 'de la empresa',
        // version a 
        'nombre':'Nombre',
        'apellidos':'Apellidos',
        'repetir_correo':'Repetir Correo:',
        'usuario':'Usuario',
        'contrasena':'Contraseña:',
        'f_nacimineto':'Fecha de nacimiento',
        'subir_foto_perfil':'Subir Foto de Perfil',
        'privacidad1':'Acepto la',
        'privacidad2':'Política de privacidad',
        'guardar':'Guardar datos y acceder',
        // confirmación
        'confirmar':'Confirmación de datos',
        'confirmar_comprar':'Confirmar y comprar',
        'modificar':'Modificar datos',
        'mensaje_confirmar':'Tu compra ha sido confirmada. A continuación se muestran los datos registrados:',
        'total_personas': 'Total de personas',
        'precio_total': 'Precio Total',
        'acompanante_singular': 'Acompañante',

        // info compra
        'inicio_sesion':'Iniciar sesión',
        'registrarse':'Registrarse',
        'reg_usuario':'Registro de Usuario',

        // sobre nosotros
        'nuestra_historia':'Nuestra historia',
        'texto_historia':'Todo comenzó con una mochila y un sueño. Éramos un grupo de amigos con una sed insaciable de explorar el mundo, de vivir experiencias auténticas y de conectar con culturas lejanas. Esa pasión nos llevó a fundad Mochileros por el Mundo, con la convicción de que viajar es más que visitar lugares; es una forma de vida, una oportunidad para crecer y para crear recuerdos que duran para siempre. ',
        'mision_vision':'Nuestra misión y visión',
        'nuestra_mision':'Nuestra misión',
        'texto_mision':'Inspirar y facilitar viajes auténticos y transformadores, conectando a las personas con el mundo de una manera responsable y enriquecedora.',
        'nuestra_vision':'Nuestra visión',
        'texto_vision':'Ser la comunidad de viajeros preferida a nivel global, reconocida por nuestra pasión, experiencia y compromiso con la aventura sostenible.',
        'nuestros_valores':'Nuestros valores',
        'texto_valores':'Aventura, respeto, sostenibilidad, autenticidad y comunidad.',
        'nuestro_equipo':'Nuestro equipo',
        'rol1':'Fundadora y CEO',
        'cita1':'"Mi mayor alegría es ver a nuestros viajeros descubrir la magia de un nuevo lugar"',
        'rol2':'Especialista en destinos de Asia',
        'cita2':'"Cada viaje es una historia y me encantaría ayudar a escribir la tuya."',
        'rol3':'Coordinador de experiencias',
        'cita3':'"Creando momentos inolvidables, un destino a la vez"',
        'rol4':'Márketing y Comunidad',
        'cita4':'"Conectando viajeros y compartiendo la pasión por explorar."',

        // información de compra
        'confirmacion_compra':'Confirmación de la compra',
        'cargando_confirmacion':'Cargando la información de la reserva...',
        'volver_inicio':'Volver al inicio',
        'ver_compra_perfil':'Ver compra en el perfil',

        //buscador 
        'limpiar':'Limpiar',
        'filtros':'Filtros',
        'tipo_viaje':'Tipo de viaje',
        'presupuesto_max':'Presupuesto máximo',
        'tope':'Hasta $2000',
        'duracion':'Duración',
        'puntuacion':'Puntuación',
        'destinos_disponibles':'Destinos disponibles',

        // comunidad
        'comunidad_t':'COMUNIDAD',
        'experiencias_otros':'Experiencias de otros usuarios',
        'descripcion_experiencia':'Descubre las historias y vivencias de otros miembros de nuestra comunidad. Inspírate y aprende de sus caminos.',
        'ver_experiencias':'Ver Experiencias',
        'consejos_otros':'Consejos de otros usuarios',
        'descripcion_consejo':'Encuentra valiosos consejos y trucos compartidos por la comunidad para ayudarte en tu propio viaje.',
        'ver_consejos':'Ver Consejos',
        'deja_consejo':'Deja tu propio consejo',
        'descripcion_dejar':'¡Tu experiencia es valiosa! Comparte tus conocimientos y ayuda a otros miembros de la comunidad.',
        'compartir_consejo':'Compartir consejo',

        // seguros 
        'seguro':'Seguro de viaje',
        'pregunta_seguro':'¿Desea contratar un seguro de viaje por 50€?',
        'si':'Sí',
        'no':'No',
        'al_seleccionar':'Al seleccionar contratarlo, obtienes cobertura para:',
        'c1':'Asistencia médica y gastos de hospitalización (hasta 50.000€).',
        'c2':'Cancelación o interrupción del viaje por causas de fuerza mayor.',
        'c3':'Pérdida, robo o retraso de equipaje.',
        'c4':'Repatriación por razones médicas.',
        'poliza1':'Puedes leer los',
        'poliza2':'términos y condiciones completos de la póliza aquí',
        'aceptar_seguro':'Acepto los términos y condiciones de la póliza de seguros',
        'tyc_poliza':'Términos y Condiciones de la Póliza de Seguros',
        't1':'El presente contrato tiene como finalidad brindar cobertura al asegurado durante sus desplazamientos nacionales e internacionales, frente a riesgos relacionados con accidentes, enfermedades, pérdida de equipaje y otros eventos especificados en la póliza.',
        't2':'Asegurado: Persona titular de la póliza que disfruta de las coberturas contratadas',
        't5':'Repatriación: Totalmente cubierta en caso de necesidad médica.',
        't6':'Repatriación: Totalmente cubierta en caso de necesidad médica.',
        't7':'Pulsa fuera de la ventana para volver a la página de seguros y aceptar los términos de la póliza.',

        // info compra 
        'pack_seleccionado': 'Pack seleccionado',
        'nombre_completo': 'Nombre completo',
        'correo_electronico': 'Correo electrónico',
        'acompanantes': 'Acompañantes',
        'viaja_mascotas': 'Viaja con mascotas',
        'tipo_mascota': 'Tipo de mascota',
        'intolerancias': 'Intolerancias / Alergias',
        'numero_personas': 'Número de personas',
        'seguro_persona': 'Seguro (por persona)',
        'precio_total': 'Precio Total',
        'telefono_emergencia': 'Teléfono de emergencia',
        'comentarios_adicionales': 'Comentarios adicionales',
        'acompanante_singular': 'Acompañante',
        'mensaje_exito_compra': 'Tu compra ha sido confirmada. A continuación se muestran los datos registrados:',
        'mensaje_error_reserva': 'No se encontró información de la reserva. Vuelve a realizar el proceso.',

        // perfil
        'perfil_usuario': 'Perfil de usuario',
        'info_perfil': 'Información del perfil',
        'nombre_usuario': 'Nombre de usuario',
        'cerrar_sesion': 'Cerrar sesión',
        'cambiar_contrasena': 'Cambiar contraseña',
        'contrasena_actual': 'Contraseña actual',
        'contrasena_nueva': 'Contraseña nueva',
        'repetir_nueva_contrasena': 'Repetir nueva contraseña',
        'cambiar_contrasena': 'Cambiar contraseña',
        'mis_compras': 'Mis compras',
        'companeros_viaje': 'Compañeros de viaje',
        'mis_consejos':'Mis consejos',
        'destinos_fav': 'Destinos favoritos',

        // perfil-compra
        'detalles_reserva': 'Detalles de la reserva',
        'datos_reserva': 'Datos de la reserva',
        'deja_reseña': 'Deja tu reseña',
        'guardar_reseña': 'Guardar reseña',
        'ir_inicio': 'Ir al inicio',
        'destinos': 'Destinos',
        // Textos dinámicos de perfil
        'fecha': 'Fecha',
        'precio': 'Precio',
        'ver_detalles': 'Ver detalles',
        'eliminar': 'Eliminar',
        'sin_compras': 'No has realizado ninguna compra todavía.',
        'sin_companeros': 'No tienes compañeros guardados.',
        'sin_favoritos': 'No tienes destinos favoritos guardados.',
        'sin_consejos': 'No has publicado ningún consejo todavía.',
        'estado': 'Estado',
        'confirmada': 'Confirmada'

    },
    'EN': {
        'destinos': 'Destinatios',
        'comunidad': 'Community',
        'otros_rincones': 'Other spots',
        'descubre_aventura': 'Discover your next adventure.',
        'destinos_increibles': 'Epxplore incredible destinations and create unforgettable mempries',
        'explorar_destinos': 'Explore destinatios.',
        'destinos_destacados': 'Outstanding destinatios.',
        'francia': 'París, France',
        'japon': 'Tokyo, Japan',
        'peru': 'Machu Picchu, Peru.',
        'ver_mas': 'See More',
        'dicen_viajeros': 'What our travelers say',
        'mensaje_joselito1': 'The best experience of my life!',
        'mensaje_carlos1': 'I love it!',
        'mensaje_ana1': 'Amazing!',
        'ir_comunidad': 'Go to community',
        'newsletter': 'Subscribe to our newsletter.',
        'recibe_info': 'Receive infromatios about your next great adventures',
        'suscribir': 'Subscribe',
        'sobre_nosotros': 'About us',
        'politica_privacidad': 'Privacy Policy',
        'ayuda': 'Help',
        // Otros rincones
        'seleccion_contiente': 'Select Continent',
        'todos_contientes': 'All Continents',
        'europa': 'EUROPE',
        'asia': 'ASIA',
        'africa': 'AFRICA',
        'america_n': 'NORTH AMERICA',
        'america_s': 'SOUTH AMERICA',
        'oceania': 'OCEANIA',
        'seleccion_pais': 'Select Country',
        'todos_paises': 'All Countries',
        'bucador_destinos': 'Search Destinations',
        'viena': 'Vienna, Austria',
        'viena1': 'Imperial city with museums and classical music at every step. Schönbrunn Palace and the Ringstrasse embody Baroque and Historicism, while cafés like Demel preserve pastry traditions. Ideal for walking through parks and opera houses.',
        'brujas': 'Bruges, Belgium',
        'brujas1': 'Perfectly preserved medieval center, tree-lined canals, and cobbled squares like the Markt. Belfries, guild houses, and chocolate shops create a fairytale atmosphere inviting you to get lost without haste.',
        'copenhague': 'Copenhagen, Denmark',
        'copenhague1': 'Balance between contemporary design and Nordic tradition. Nyhavn, Tivoli, and cycling districts show a human and welcoming city; avant-garde cuisine and respect for public space.',
        'luibliana': 'Ljubljana, Slovenia',
        'luibliana1': 'Small and scenic capital, with a pedestrian center, riverside cafés, and a castle on high. Ideal base for trips to Lake Bled and the Julian Alps.',
        'barcelona': 'Barcelona, Spain',
        'barcelona1': 'Gaudi’s Modernism, sea, and mountains on the same plane. The Sagrada Familia, Park Güell, and neighborhood life coexist with markets and museums; walks from Montjuïc to the beaches.',
        'sevilla': 'Seville, Spain',
        'sevilla1': 'Monumental historic center, patios, and tiles. The Alcázar, the Cathedral, and the Santa Cruz neighborhood add to a powerful tapas culture and flamenco.',
        'tallin': 'Tallinn, Estonia',
        'tallin1': 'Walled medieval old town, towers, and colorful roofs overlooking the Baltic. Cold winters, but photogenic views from Toompea.',
        'paris': 'Paris, France',
        'paris1': 'Urban romance: Seine, boulevards, and iconic museums. Neighborhoods with their own identity and street-side cafés; Notre Dame, Sacré-Coeur, and the Eiffel Tower as essential landmarks.',
        'budapest': 'Budapest, Hungary',
        'budapest1': 'Art Nouveau architecture, thermal baths, and evening walks along the Danube. The Parliament shines at dusk from the Chain Bridge.',
        'florencia': 'Florence, Italy',
        'florencia1': 'Cradle of the Renaissance: Duomo, Uffizi, and crafts in the Oltrarno. A living museum-city where every street holds sculptures, palaces, and workshops.',
        'roma': 'Rome, Italy',
        'roma1': 'The "Eternal City" combines classical ruins, Baroque squares, and neighborhood life. From the Pantheon to the Trevi Fountain, history coexists with trattorias and terraces.',
        'venecia': 'Venice, Italy',
        'venecia1': 'Car-free with a unique aquatic layout. Canals, palaces, and bridges connect islands; from San Marco to quieter districts, it is pure contemplation.',
        'valeta': 'Valletta, Malta',
        'valeta1': 'Fortified and Baroque, with viewpoints over the Grand Harbour. Palaces, churches, and museums concentrated in a compact, walkable center.',
        'bergen': 'Bergen, Norway',
        'bergen1': 'Wooden houses in Bryggen, a lively port, and mountains falling into fjords. Perfect starting point for scenic routes.',
        'amsterdam': 'Amsterdam, Netherlands',
        'amsterdam1': 'UNESCO Heritage canals, narrow gables, and cycling culture. World-class museums and green neighborhoods connected by bridges.',
        'oporto': 'Porto, Portugal',
        'oporto1': 'Tiles, bridges over the Douro, and Port wine cellars. Lello Bookstore and Leça pools as contemporary icons.',
        'londres': 'London, United Kingdom',
        'londres1': 'History and avant-garde on the banks of the Thames. Free museums, immense parks, and an endless cultural and gastronomic scene.',
        'edimburgo': 'Edinburgh, United Kingdom',
        'edimburgo1': 'Royal Mile, castle, and green hills. The volcanic rock of Arthur’s Seat offers an exceptional panorama over the stone city.',
        'praga': 'Prague, Czech Republic',
        'praga1': 'Gothic domes and towers over a photogenic old town. Charles Bridge at sunrise and historic cafés with music and literature.',
        'lucerna': 'Lucerne, Switzerland', 
        'lucerna1': 'Lake, nearby mountains, and the Kapellbrücke as a postcard. Medieval roofs and alpine air just minutes from mountain trails.',
        'zurich': 'Zurich, Switzerland',
        'zurich1': 'Elegant old town by the lake, museums, galleries, and life by the water. Vibrant summers and Swiss efficiency in every detail.',
        'reikiavik': 'Reykjavik, Iceland',
        'reikiavik1': 'Gateway to geysers and waterfalls. Colorful houses, Harpa concert hall, and geothermal pools nearby.',
        'beijing': 'Beijing, China',
        'beijing1': 'Imperial capital with the Forbidden City, hutongs, and wide avenues. Gateway to nearby sections of the Great Wall and rich regional cuisine.',
        'hong': 'Hong Kong, China',
        'hong1': 'Dense skyline around a ferry-filled harbor. Mountains, islands, and nature reserves minutes from the financial center.',
        'seul': 'Seoul, South Korea',
        'seul1': 'Skyscrapers and palaces, night markets, and an impeccable subway network. Districts like Bukchon and Myeongdong show tradition and fashion.',
        'jaipur': 'Jaipur, India',
        'jaipur1': 'The "Pink City": Hawa Mahal, forts, and salmon-colored bazaars. Crafts, jewelry, and Rajasthani cuisine in palaces and streets.',
        'kioto': 'Kioto, Japan', 
        'kioto1': 'Temples, shrines, and classic gardens. Hanami in spring, tree-lined routes, and the chance to spot geishas in Gion.',
        'luang': 'Luang Prabang, Laos',
        'luang1': 'UNESCO Heritage at the confluence of rivers. Monk processions at dawn, nearby waterfalls, and colonial-Buddhist architecture.',
        'beirut': 'Beirut, Lebanon',
        'beirut1': 'Beaches, clubs, and rooftops facing mosques and historic souks. Gastronomy and nightlife with a Mediterranean and Levantine flair.',
        'mascate': 'Muscat, Oman',
        'mascate1': 'Bays and mountains framing mosques, souks, and Portuguese forts. Coastal walks and white architecture by the Gulf of Oman.',
        'doha': 'Doha, Qatar',
        'doha1': 'Corniche with futuristic skyline, Souq Waqif, and I. M. Pei’s Museum of Islamic Art. A mix of tradition and new cultural areas.',
        'mai': 'Chiang Mai, Thailand',
        'mai1': 'Hillside temples, cafés, and creative markets. Starting point for northern nature and intense culinary experiences.',
        'hanoi': 'Hanoi, Vietnam',
        'hanoi1': 'Lakes, temples, and French quarter with a romantic air. Narrow streets with traditional cafés and vibrant markets.',
        'singapur': 'Singapore, Singapore',
        'singapur1': 'Garden city with urban jungle, Botanic Gardens, and Gardens by the Bay. Temples, heritage houses, and impeccable logistics for getting around.',
        'chef': 'Chefchaouen, Morocco',
        'chef1': 'Blue medina among the Rif mountains. Painted alleys, artisan doors, and nearby viewpoints to see the whole town from above.',
        'cabo': 'Cape Town, South Africa',
        'cabo1': 'Table Mountain, penguin beaches, and colorful neighborhoods like Bo-Kaap. Gardens, nearby vineyards, and scenic coastal routes.',
        'sidney': 'Sydney, Australia',
        'sidney1': 'Iconic Opera House, navigable harbor, and urban beaches like Bondi. Daily ferries and parks facing the water.',
        'queen': 'Queenstown, New Zealand',
        'queen1': 'Adrenaline capital between lake and mountains. Natural viewpoints, adventures, and cinematic landscapes.',
        'quebec': 'Quebec City, Canada',
        'quebec1': 'Walled town on high overlooking the St. Lawrence. European atmosphere, steep roofs, and pink sunsets.',
        'ny': 'New York, United States',
        'ny1': 'Iconic architecture, parks like Central Park, and an incomparable art scene. Urban energy that never turns off.',
        'sf': 'San Francisco, United States',
        'sf1': 'Golden Gate Bridge, hills, and Victorian houses. World-class museums and neighborhoods with their own character.',
        'sm': 'San Miguel de Allende, Mexico',
        'sm1': 'Colonial center with a pink neo-Gothic parish church. Cobbled streets, courtyards, and art in galleries and workshops.',
        'ba': 'Buenos Aires, Argentina',
        'ba1': 'Neighborhoods with identity (Recoleta, San Telmo, La Boca), varied architecture, and intense cultural life. Tango, steakhouses, and bookstores in emblematic buildings.',
        'rio': 'Rio de Janeiro, Brazil',
        'rio1': 'Mythical beaches, urban jungle, and Christ the Redeemer watching over bays and hills. Samba rhythm in streets and squares.',
        'cartagena': 'Cartagena, Colombia',
        'cartagena1': 'Walls, squares, and colonial mansions covered in bougainvillea. Getsemaní and Bocagrande show its creative and modern side.',
        'quito': 'Quito, Ecuador',
        'quito1': 'Golden historic center under Andean volcanoes. Views from the Basilica of the National Vow and traditional markets.',
        'cuzco': 'Cusco, Peru',
        'cuzco1': 'Ancient Inca capital with squares, convents, and cobbled streets. Starting point for Machu Picchu and viewpoints like the White Christ.',
        // Compra (Páginas individuales y Pasos)
        'titulo_brasil': 'Rhythm and Nature in Brazil',
        'titulo_japon': 'Japan, Tradition and Modernity',
        'titulo_francia': 'Art in the French Streets',
        'titulo_noruega': 'Dream Landscapes in Norway',
        'titulo_italia': 'Discover the Beauty of Italy',
        'titulo_marruecos': 'Colors and Aromas of Morocco',
        
        'descripcion_brasil': 'Live the energy of Rio, explore the Amazon rainforest, and relax on its tropical beaches.',
        'descripcion_japon': 'Immerse yourself in Japanese culture and discover its millenary traditions.',
        'descripcion_noruega': 'Dare to explore the magic of the fjords and fascinating Scandinavian history.',
        'descripcion_francia': 'Tour Paris, Provence, and the French Riviera amidst art, culture, and unforgettable flavors.',
        'descripcion_italia': 'Discover the beauty of Italy through its landscapes, culture, and gastronomy.',
        'descripcion_marruecos': 'Let yourself be carried away by the senses on an unforgettable journey through the Berber world.',
        
        'descripcion_pack': 'Pack Description:',
        'texto_pack_brasil': 'A tour of the best of Brazil: Rio de Janeiro and its beaches, the incredible biodiversity of the Amazon, and the country\'s vibrant culture with music, dance, and gastronomy. Ideal for those seeking a mix of nature and partying.',
        'texto_pack_japon': 'Immerse yourself in Japanese culture and discover its millenary traditions: behold the majesty of Mount Fuji, explore the ancient temples of Kyoto, and enjoy the vibrant urban life of Tokyo. This 11-day trip will take you through a fascinating mix of history, technology, and nature, offering an unforgettable experience in the heart of Japan.',
        'texto_pack_noruega': 'Dare to explore the magic of the majestic Norwegian fjords, discover fascinating Viking history, and immerse yourself in natural landscapes that seem straight out of a dream. This trip combines adventure, Scandinavian culture, and northern tranquility, offering an unforgettable experience for those seeking to connect with nature and history in a unique region.',
        'texto_pack_francia': 'Discover France\'s cultural richness: stroll through the streets of Paris, visit iconic museums like the Louvre, enjoy French cuisine at local markets, and explore the beauty of Provence and the Côte d\'Azur. A trip designed for lovers of art, history, and gastronomy.',
        'texto_pack_italia': 'Tour historic cities like Rome and Florence, enjoy authentic pasta, pizza, and local wines, and immerse yourself in traditions and monuments that make Italy unique. This trip combines adventure, history, and culinary pleasure in an unforgettable experience for those wanting to explore the best of the country authentically.',
        'texto_pack_marruecos': 'Let yourself be carried away by the senses on an unforgettable journey through the Berber world: explore desert landscapes and the Atlas Mountains, discover the hospitality of its villages, their colors, aromas, and ancient traditions. An experience combining adventure, culture, and authenticity in every corner of Morocco.',
        
        'info_personal': 'Personal Information',
        'nombre_completo': 'Full Name:',
        'correo': 'Email Address',
        'ciudad': 'City',
        'c_postal': 'Postal Code:',
        'telefono_contacto': 'Contact Phone:',
        'siguiente': 'Next',
        'borrar': 'Clear',
        
        // Pago
        'formulario_compra': 'Purchase Form',
        'tipo_tarjeta': 'Card Type:',
        'seleccion_opcion': 'Select an option',
        'num_tarjeta': 'Card Number:',
        'titular_tarjeta': 'Cardholder Name',
        'fecha_caducidad': 'Expiry Date',
        'codigo_cvv': 'CVV Code:',
        'volver': 'Back',
        
        // Ampliación del pago
        'revisar': 'Review your details and complete the extension',
        'revisar2': 'Verify the data from the previous step and add necessary additional information.',
        'info_adicional': 'Additional Information',
        'acompanante': 'Companions:',
        'mascotas': 'Traveling with pets:',
        'si': 'Yes',
        'alergias': 'Intolerances / Allergies:',
        'coment_adicional': 'Additional Comments',
        'condiciones1': 'I accept the ',
        'condiciones2': 'terms and conditions',
        'condiciones3': ' of the company',
        
        // Version A (Registro)
        'nombre': 'Name',
        'apellidos': 'Last Name',
        'repetir_correo': 'Repeat Email:',
        'usuario': 'Username',
        'contrasena': 'Password:',
        'f_nacimineto': 'Date of Birth',
        'subir_foto_perfil': 'Upload Profile Photo',
        'privacidad1': 'I accept the ',
        'privacidad2': 'Privacy Policy',
        'guardar': 'Save and Access',

        // Confirmación
        'confirmar': 'Data Confirmation',
        'confirmar_comprar': 'Confirm and Buy',
        'modificar': 'Modify Details',
        'mensaje_confirmar': 'Your purchase has been confirmed. The registered details are shown below:',
        'total_personas': 'Total people',
        'precio_total': 'Total Price',
        'acompanante_singular': 'Companion',

        // Info Compra (Login/Register)
        'inicio_sesion': 'Log In',
        'registrarse': 'Sign Up',
        'reg_usuario': 'User Registration',

        // Sobre Nosotros
        'nuestra_historia': 'Our History',
        'texto_historia': 'It all started with a backpack and a dream. We were a group of friends with an insatiable thirst to explore the world, live authentic experiences, and connect with distant cultures. That passion led us to found Mochileros por el Mundo, with the conviction that travel is more than visiting places; it is a way of life, an opportunity to grow, and to create memories that last forever.',
        'mision_vision': 'Our Mission and Vision',
        'nuestra_mision': 'Our Mission',
        'texto_mision': 'To inspire and facilitate authentic and transformative trips, connecting people with the world in a responsible and enriching way.',
        'nuestra_vision': 'Our Vision',
        'texto_vision': 'To be the preferred global community of travelers, recognized for our passion, experience, and commitment to sustainable adventure.',
        'nuestros_valores': 'Our Values',
        'texto_valores': 'Adventure, respect, sustainability, authenticity, and community.',
        'nuestro_equipo': 'Our Team',
        'rol1': 'Founder & CEO',
        'cita1': '"My greatest joy is seeing our travelers discover the magic of a new place"',
        'rol2': 'Asia Destination Specialist',
        'cita2': '"Every trip is a story and I would love to help write yours."',
        'rol3': 'Experience Coordinator',
        'cita3': '"Creating unforgettable moments, one destination at a time"',
        'rol4': 'Marketing & Community',
        'cita4': '"Connecting travelers and sharing the passion for exploring."',

        // Información de compra
        'confirmacion_compra': 'Purchase Confirmation',
        'cargando_confirmacion': 'Loading booking information...',
        'volver_inicio': 'Back to Home',
        'ver_compra_perfil': 'View purchase in profile',

        // Buscador 
        'limpiar': 'Clear',
        'filtros': 'Filters',
        'tipo_viaje': 'Travel Type',
        'presupuesto_max': 'Max Budget',
        'tope': 'Up to $2000',
        'duracion': 'Duration',
        'puntuacion': 'Rating',
        'destinos_disponibles': 'Available Destinations',

        // Comunidad
        'comunidad_t': 'COMMUNITY',
        'experiencias_otros': 'Experiences from other users',
        'descripcion_experiencia': 'Discover the stories and experiences of other members of our community. Get inspired and learn from their paths.',
        'ver_experiencias': 'View Experiences',
        'consejos_otros': 'Tips from other users',
        'descripcion_consejo': 'Find valuable tips and tricks shared by the community to help you on your own journey.',
        'ver_consejos': 'View Tips',
        'deja_consejo': 'Leave your own tip',
        'descripcion_dejar': 'Your experience is valuable! Share your knowledge and help other community members.',
        'compartir_consejo': 'Share Tip',

        // Seguros 
        'seguro': 'Travel Insurance',
        'pregunta_seguro': 'Do you want to add travel insurance for €50?',
        'si': 'Yes',
        'no': 'No',
        'al_seleccionar': 'By selecting it, you get coverage for:',
        'c1': 'Medical assistance and hospitalization expenses (up to €50,000).',
        'c2': 'Trip cancellation or interruption due to force majeure.',
        'c3': 'Loss, theft, or delay of luggage.',
        'c4': 'Repatriation for medical reasons.',
        'poliza1': 'You can read the ',
        'poliza2': 'complete terms and conditions of the policy here',
        'aceptar_seguro': 'I accept the terms and conditions of the insurance policy',
        'tyc_poliza': 'Insurance Policy Terms and Conditions',
        't1': 'The purpose of this contract is to provide coverage to the insured during national and international travel, against risks related to accidents, illness, loss of luggage, and other events specified in the policy.',
        't2': 'Insured: The policyholder who is entitled to the contracted coverage.',
        't5': 'Repatriation: Fully covered in case of medical necessity.',
        't6': 'Repatriation: Fully covered in case of medical necessity.',
        't7': 'Click outside the window to return to the insurance page and accept the policy terms.',

        // info compra
        'pack_seleccionado': 'Selected Pack',
        'nombre_completo': 'Full Name',
        'correo_electronico': 'Email Address',
        'acompanantes': 'Companions',
        'viaja_mascotas': 'Traveling with pets',
        'tipo_mascota': 'Type of pet',
        'intolerancias': 'Intolerances / Allergies',
        'numero_personas': 'Number of people',
        'seguro_persona': 'Insurance (per person)',
        'precio_total': 'Total Price',
        'telefono_emergencia': 'Emergency Phone',
        'comentarios_adicionales': 'Additional Comments',
        'acompanante_singular': 'Companion',
        'mensaje_exito_compra': 'Your purchase has been confirmed. The registered details are shown below:',
        'mensaje_error_reserva': 'Booking information not found. Please try again.',

        // Perfil
        'perfil_usuario': 'User Profile',
        'info_perfil': 'Profile Information',
        'nombre_usuario': 'Username',
        'cerrar_sesion': 'Log Out',
        'cambiar_contrasena': 'Change Password',
        'contrasena_actual': 'Current Password',
        'contrasena_nueva': 'New Password',
        'repetir_nueva_contrasena': 'Repeat New Password',
        'mis_compras': 'My Purchases',
        'mis_consejos': 'My Tips',
        'companeros_viaje': 'Travel Companions',
        'destinos_fav': 'Favorite Destinations',

        // Perfil Compra (Detalles)
        'detalles_reserva': 'Booking Details',
        'datos_reserva': 'Reservation Data',
        'deja_reseña': 'Leave a Review',
        'guardar_reseña': 'Save Review',
        'ir_inicio': 'Go to Home',
        'destinos': 'Destinations',
        // Profile dynamic texts
        'fecha': 'Date',
        'precio': 'Price',
        'ver_detalles': 'View Details',
        'eliminar': 'Remove',
        'sin_compras': 'You have not made any purchases yet.',
        'sin_companeros': 'You have no saved companions.',
        'sin_favoritos': 'You have no saved favorite destinations.',
        'sin_consejos': 'You have not posted any tips yet.',
        'estado': 'Status',
        'confirmada': 'Confirmed'
    },
    'FR': {
        'destinos': 'Destinations',
        'comunidad': 'Communauté',
        'otros_rincones': 'Autres coins',
        'descubre_aventura': 'Découvrez votre prochaine aventure.',
        'destinos_increibles': 'Explorez des destinations incroyables et créez des souvenirs inoubliables',
        'explorar_destinos': 'Explorer les destinations',
        'destinos_destacados': 'Destinations phares',
        'francia': 'Paris, France',
        'japon': 'Tokyo, Japon',
        'peru': 'Machu Picchu, Pérou',
        'ver_mas': 'Voir plus',
        'dicen_viajeros': 'Ce que disent nos voyageurs',
        'mensaje_joselito1': 'La meilleure expérience de ma vie !',
        'mensaje_carlos1': 'Je l` aime!',
        'mensaje_ana1': 'Incroyable!',
        'ir_comunidad': 'Aller à la communauté',
        'newsletter': 'Abonnez-vous à notre newsletter',
        'recibe_info': 'Recevez des informations sur vos prochaines grandes aventures',
        'suscribir': 'S\'abonner',
        'sobre_nosotros': 'À propos de nous',
        'politica_privacidad': 'Politique de confidentialité',
        'ayuda': 'Aide',
        // Otros rincones
        'seleccion_contiente': 'Sélectionner un continent',
        'todos_contientes': 'Tous les continents',
        'europa': 'EUROPE',
        'asia': 'ASIE',
        'africa': 'AFRIQUE',
        'america_n': 'AMÉRIQUE DU NORD',
        'america_s': 'AMÉRIQUE DU SUD',
        'oceania': 'OCÉANIE',
        'seleccion_pais': 'Sélectionner un pays',
        'todos_paises': 'Tous les pays',
        'bucador_destinos': 'Rechercher des destinations',
        'viena': 'Vienne, Autriche',
        'viena1': 'Cité impériale avec musées et musique classique à chaque pas. Le château de Schönbrunn et le Ringstrasse condensent le baroque et l\'historisme, tandis que des cafés comme Demel perpétuent la tradition pâtissière.',
        'brujas': 'Bruges, Belgique',
        'brujas1': 'Centre médiéval parfaitement conservé, canaux bordés d\'arbres et places pavées comme le Markt. Beffrois, maisons de guildes et chocolateries créent une ambiance de conte de fées.',
        'copenhague': 'Copenhague, Danemark',
        'copenhague1': 'Équilibre entre design contemporain et tradition nordique. Nyhavn, Tivoli et quartiers cyclables montrent une ville humaine et accueillante ; gastronomie d\'avant-garde.',
        'luibliana': 'Ljubljana, Slovénie',
        'luibliana1': 'Capitale petite et scénique, avec centre piétonnier, cafés au bord de la rivière et château sur les hauteurs. Base idéale pour le lac de Bled et les Alpes juliennes.',
        'barcelona': 'Barcelone, Espagne',
        'barcelona1': 'Modernisme de Gaudí, mer et montagne sur un même plan. La Sagrada Familia, le Parc Güell et la vie de quartier coexistent avec marchés et musées.',
        'sevilla': 'Séville, Espagne',
        'sevilla1': 'Centre historique monumental, patios et azulejos. L\'Alcazar, la Cathédrale et le quartier de Santa Cruz s\'ajoutent à une puissante culture de tapas et au flamenco.',
        'tallin': 'Tallinn, Estonie',
        'tallin1': 'Vieille ville médiévale fortifiée, tours et toits colorés avec vue sur la Baltique. Hiver froid, mais photogénique depuis Toompea.',
        'paris': 'Paris, France',
        'paris1': 'Romance urbaine : Seine, boulevards et musées emblématiques. Quartiers avec leur propre identité et cafés en terrasse ; Notre-Dame, Sacré-Cœur et Tour Eiffel incontournables.',
        'budapest': 'Budapest, Hongrie',
        'budapest1': 'Architecture Art Nouveau, bains thermaux et promenades nocturnes sur le Danube. Le Parlement brille au crépuscule depuis le Pont des Chaînes.',
        'florencia': 'Florence, Italie',
        'florencia1': 'Berceau de la Renaissance : Duomo, Offices et artisanat dans l\'Oltrarno. Une ville-musée vivante où chaque rue abrite sculptures, palais et ateliers.',
        'roma': 'Rome, Italie',
        'roma1': 'La "Ville Éternelle" combine ruines classiques, places baroques et vie de quartier. Du Panthéon à la Fontaine de Trevi, l\'histoire côtoie les trattorias.',
        'venecia': 'Venise, Italie',
        'venecia1': 'Sans voitures et avec un tracé aquatique unique. Canaux, palais et ponts relient les îles ; de Saint-Marc aux quartiers plus calmes, c\'est la pure contemplation.',
        'valeta': 'La Valette, Malte',
        'valeta1': 'Fortifiée et baroque, avec des belvédères sur le Grand Port. Palais, églises et musées concentrés dans un centre compact et accessible à pied.',
        'bergen': 'Bergen, Norvège',
        'bergen1': 'Maisons en bois à Bryggen, port vivant et montagnes tombant dans les fjords. Point de départ idéal pour des routes panoramiques.',
        'amsterdam': 'Amsterdam, Pays-Bas',
        'amsterdam1': 'Canaux classés UNESCO, pignons étroits et culture cycliste. Musées de premier plan et quartiers verts reliés par des ponts.',
        'oporto': 'Porto, Portugal',
        'oporto1': 'Azulejos, ponts sur le Douro et caves de vin de Porto. Librairie Lello et piscines de Leça comme icônes contemporaines.',
        'londres': 'Londres, Royaume-Uni',
        'londres1': 'Histoire et avant-garde sur les rives de la Tamise. Musées gratuits, parcs immenses et une scène culturelle et gastronomique inépuisable.',
        'edimburgo': 'Édimbourg, Royaume-Uni',
        'edimburgo1': 'Royal Mile, château et collines vertes. La roche volcanique d\'Arthur’s Seat offre un panorama exceptionnel sur la ville de pierre.',
        'praga': 'Prague, République Tchèque',
        'praga1': 'Coupoles et tours gothiques sur une vieille ville photogénique. Pont Charles au lever du soleil et cafés historiques avec musique et littérature.',
        'lucerna': 'Lucerne, Suisse',
        'lucerna1': 'Lac, monts proches et le Kapellbrücke en carte postale. Toits médiévaux et air alpin à quelques minutes des sentiers de montagne.',
        'zurich': 'Zurich, Suisse',
        'zurich1': 'Vieille ville élégante au bord du lac, musées, galeries et vie au bord de l\'eau. Étés vibrants et efficacité suisse dans chaque détail.',
        'reikiavik': 'Reykjavik, Islande',
        'reikiavik1': 'Porte d\'entrée vers les geysers et cascades. Maisons colorées, salle Harpa et piscines géothermiques à proximité.',
        'beijing': 'Pékin, Chine',
        'beijing1': 'Capitale impériale avec la Cité Interdite, les hutongs et de larges avenues. Porte vers la Grande Muraille et une cuisine régionale riche.',
        'hong': 'Hong Kong, Chine',
        'hong1': 'Horizon dense autour d\'un port rempli de ferrys. Montagnes, îles et réserves naturelles à quelques minutes du centre financier.',
        'seul': 'Séoul, Corée du Sud',
        'seul1': 'Gratte-ciels et palais, marchés nocturnes et métro impeccable. Des quartiers comme Bukchon et Myeongdong montrent tradition et mode.',
        'jaipur': 'Jaipur, Inde',
        'jaipur1': 'La "Ville Rose" : Hawa Mahal, forts et bazars couleur saumon. Artisanat, bijoux et gastronomie du Rajasthan dans les palais et les rues.',
        'kioto': 'Kioto, Japon',
        'kioto1': 'Temples, sanctuaires et jardins classiques. Hanami au printemps, routes bordées d\'arbres et possibilité de croiser des geishas à Gion.',
        'luang': 'Luang Prabang, Laos',
        'luang1': 'Patrimoine UNESCO au confluent des rivières. Processions de moines à l\'aube, cascades proches et architecture coloniale-bouddhiste.',
        'beirut': 'Beyrouth, Liban',
        'beirut1': 'Plages, clubs et toits-terrasses face aux mosquées et souks historiques. Gastronomie et vie nocturne à l\'air méditerranéen et levantin.',
        'mascate': 'Mascate, Oman',
        'mascate1': 'Baies et montagnes encadrant mosquées, souks et forts portugais. Promenades côtières et architecture blanche près du Golfe d\'Oman.',
        'doha': 'Doha, Qatar',
        'doha1': 'Corniche avec horizon futuriste, Souq Waqif et Musée d\'Art Islamique. Mélange de tradition et de nouvelles zones culturelles.',
        'mai': 'Chiang Mai, Thaïlande',
        'mai1': 'Temples à flanc de colline, cafés et marchés créatifs. Point de départ pour la nature du nord et des expériences culinaires intenses.',
        'hanoi': 'Hanoï, Vietnam',
        'hanoi1': 'Lacs, temples et quartier français à l\'air romantique. Rues étroites avec cafés traditionnels et marchés vibrants.',
        'singapur': 'Singapour, Singapour',
        'singapur1': 'Ville-jardin avec jungle urbaine, Jardin Botanique et Gardens by the Bay. Temples, maisons patrimoniales et logistique impeccable.',
        'chef': 'Chefchaouen, Maroc',
        'chef1': 'Médina bleue dans les montagnes du Rif. Ruelles peintes, portes artisanales et belvédères proches pour voir l\'ensemble d\'en haut.',
        'cabo': 'Le Cap, Afrique du Sud',
        'cabo1': 'Montagne de la Table, plages aux manchots et quartiers colorés comme Bo-Kaap. Jardins, vignobles proches et routes côtières.',
        'sidney': 'Sydney, Australie',
        'sidney1': 'Opéra emblématique, port navigable et plages urbaines comme Bondi. Ferrys quotidiens et parcs face à l\'eau.',
        'queen': 'Queenstown, Nouvelle-Zélande',
        'queen1': 'Capitale de l\'adrénaline entre lac et montagnes. Belvédères naturels, aventures et paysages cinématographiques.',
        'quebec': 'Québec, Canada',
        'quebec1': 'Ville fortifiée en hauteur avec vue sur le Saint-Laurent. Ambiance européenne, toits pentus et couchers de soleil roses.',
        'ny': 'New York, États-Unis',
        'ny1': 'Architecture emblématique, parcs comme Central Park et scène artistique incomparable. Énergie urbaine qui ne s\'éteint jamais.',
        'sf': 'San Francisco, États-Unis',
        'sf1': 'Pont Golden Gate, collines et maisons victoriennes. Musées de classe mondiale et quartiers avec leur propre caractère.',
        'sm': 'San Miguel de Allende, Mexique',
        'sm1': 'Centre colonial avec paroisse néogothique rose. Rues pavées, patios et art dans les galeries et ateliers.',
        'ba': 'Buenos Aires, Argentine',
        'ba1': 'Quartiers avec identité (Recoleta, San Telmo, La Boca), architecture variée et vie culturelle intense. Tango, grillades et librairies.',
        'rio': 'Rio de Janeiro, Brésil',
        'rio1': 'Plages mythiques, jungle urbaine et Christ Rédempteur veillant sur les baies. Rythme de samba dans les rues et les places.',
        'cartagena': 'Carthagène, Colombie',
        'cartagena1': 'Murailles, places et demeures coloniales couvertes de bougainvilliers. Getsemaní et Bocagrande montrent son visage créatif et moderne.',
        'quito': 'Quito, Équateur',
        'quito1': 'Centre historique doré sous les volcans andins. Vues depuis la Basilique du Vœu National et marchés traditionnels.',
        'cuzco': 'Cusco, Pérou',
        'cuzco1': 'Ancienne capitale inca avec places, couvents et rues pavées. Point de départ pour le Machu Picchu et belvédères comme le Christ Blanc.',
        // Compra (Páginas individuales y Pasos)
        'titulo_brasil': 'Rythme et Nature au Brésil',
        'titulo_japon': 'Japon, Tradition et Modernité',
        'titulo_francia': 'L\'Art dans les Rues Françaises',
        'titulo_noruega': 'Paysages de Rêve en Norvège',
        'titulo_italia': 'Découvrez la Beauté de l\'Italie',
        'titulo_marruecos': 'Couleurs et Parfums du Maroc',
        
        'descripcion_brasil': 'Vivez l\'énergie de Rio, explorez la forêt amazonienne et détendez-vous sur ses plages tropicales.',
        'descripcion_japon': 'Plongez dans la culture japonaise et découvrez ses traditions millénaires.',
        'descripcion_noruega': 'Osez explorer la magie des fjords et la fascinante histoire scandinave.',
        'descripcion_francia': 'Parcourez Paris, la Provence et la Côte d\'Azur entre art, culture et saveurs inoubliables.',
        'descripcion_italia': 'Découvrez la beauté de l\'Italie à travers ses paysages, sa culture et sa gastronomie.',
        'descripcion_marruecos': 'Laissez-vous emporter par vos sens dans un voyage inoubliable à travers le monde berbère.',
        
        'descripcion_pack': 'Description du pack :',
        'texto_pack_brasil': 'Un parcours à travers le meilleur du Brésil : Rio de Janeiro et ses plages, l\'incroyable biodiversité de l\'Amazonie et la culture vibrante du pays avec musique, danse et gastronomie. Idéal pour ceux qui cherchent un mélange de nature et de fête.',
        'texto_pack_japon': 'Plongez dans la culture japonaise et découvrez ses traditions millénaires : contemplez la majesté du Mont Fuji, explorez les temples ancestraux de Kyoto et profitez de la vie urbaine vibrante de Tokyo. Ce voyage de 11 jours vous emmènera à travers un mélange fascinant d\'histoire, de technologie et de nature, vous offrant une expérience inoubliable au cœur du Japon.',
        'texto_pack_noruega': 'Osez explorer la magie des majestueux fjords norvégiens, découvrez la fascinante histoire viking et plongez dans des paysages naturels qui semblent tout droit sortis d\'un rêve. Ce voyage combine aventure, culture scandinave et tranquillité du nord, offrant une expérience inoubliable pour ceux qui cherchent à se connecter avec la nature et l\'histoire d\'une région unique au monde.',
        'texto_pack_francia': 'Découvrez la richesse culturelle de la France : flânez dans les rues de Paris, visitez des musées emblématiques comme le Louvre, profitez de la cuisine française sur les marchés locaux et explorez la beauté de la Provence et de la Côte d\'Azur. Un voyage pensé pour les amateurs d\'art, d\'histoire et de gastronomie.',
        'texto_pack_italia': 'Parcourez des villes historiques comme Rome et Florence, savourez d\'authentiques pâtes, pizzas et vins locaux, et plongez dans des traditions et monuments qui font de l\'Italie un pays unique. Ce voyage combine aventure, histoire et plaisir culinaire dans une expérience inoubliable pour ceux qui veulent explorer le meilleur du pays de manière authentique.',
        'texto_pack_marruecos': 'Laissez-vous emporter par vos sens dans un voyage inoubliable à travers le monde berbère : explorez les paysages désertiques et les montagnes de l\'Atlas, découvrez l\'hospitalité de ses villages, leurs couleurs, arômes et traditions ancestrales. Une expérience qui combine aventure, culture et authenticité dans chaque recoin du Maroc.',
        
        'info_personal': 'Informations personnelles',
        'nombre_completo': 'Nom complet :',
        'correo': 'Adresse e-mail',
        'ciudad': 'Ville',
        'c_postal': 'Code postal :',
        'telefono_contacto': 'Téléphone de contact :',
        'siguiente': 'Suivant',
        'borrar': 'Effacer',
        
        // Pago
        'formulario_compra': 'Formulaire d\'achat',
        'tipo_tarjeta': 'Type de carte :',
        'seleccion_opcion': 'Sélectionnez une option',
        'num_tarjeta': 'Numéro de carte :',
        'titular_tarjeta': 'Titulaire de la carte',
        'fecha_caducidad': 'Date d\'expiration',
        'codigo_cvv': 'Code CVV :',
        'volver': 'Retour',
        
        // Ampliación del pago
        'revisar': 'Vérifiez vos données et complétez l\'extension',
        'revisar2': 'Vérifiez les données de l\'étape précédente et ajoutez les informations supplémentaires nécessaires.',
        'info_adicional': 'Informations supplémentaires',
        'acompanante': 'Accompagnateurs :',
        'mascotas': 'Je voyage avec des animaux :',
        'si': 'Oui',
        'alergias': 'Intolérances / Allergies :',
        'coment_adicional': 'Commentaires supplémentaires',
        'condiciones1': 'J\'accepte les ',
        'condiciones2': 'termes et conditions',
        'condiciones3': ' de l\'entreprise',
        
        // Version A (Registro)
        'nombre': 'Prénom',
        'apellidos': 'Nom de famille',
        'repetir_correo': 'Répéter l\'e-mail :',
        'usuario': 'Nom d\'utilisateur',
        'contrasena': 'Mot de passe :',
        'f_nacimineto': 'Date de naissance',
        'subir_foto_perfil': 'Télécharger photo de profil',
        'privacidad1': 'J\'accepte la ',
        'privacidad2': 'Politique de confidentialité',
        'guardar': 'Enregistrer et accéder',

        // Confirmación compra
        'confirmar': 'Confirmation des données',
        'confirmar_comprar': 'Confirmer et acheter',
        'modificar': 'Modifier les données',
        'mensaje_confirmar': 'Votre achat a été confirmé. Voici les détails enregistrés :',
        'total_personas': 'Nombre total de personnes',
        'precio_total': 'Prix Total',
        'acompanante_singular': 'Compagnon',

        // Info Compra (Login/Register)
        'inicio_sesion': 'Se connecter',
        'registrarse': 'S\'inscrire',
        'reg_usuario': 'Inscription de l\'utilisateur',

        // Sobre Nosotros
        'nuestra_historia': 'Notre histoire',
        'texto_historia': 'Tout a commencé avec un sac à dos et un rêve. Nous étions un groupe d\'amis avec une soif insatiable d\'explorer le monde, de vivre des expériences authentiques et de se connecter avec des cultures lointaines. Cette passion nous a amenés à fonder Mochileros por el Mundo, avec la conviction que voyager est plus que visiter des lieux ; c\'est un mode de vie, une opportunité de grandir et de créer des souvenirs qui durent pour toujours.',
        'mision_vision': 'Notre mission et vision',
        'nuestra_mision': 'Notre mission',
        'texto_mision': 'Inspirer et faciliter des voyages authentiques et transformateurs, en connectant les gens avec le monde de manière responsable et enrichissante.',
        'nuestra_vision': 'Notre vision',
        'texto_vision': 'Être la communauté de voyageurs préférée au niveau mondial, reconnue pour notre passion, notre expérience et notre engagement envers l\'aventure durable.',
        'nuestros_valores': 'Nos valeurs',
        'texto_valores': 'Aventure, respect, durabilité, authenticité et communauté.',
        'nuestro_equipo': 'Notre équipe',
        'rol1': 'Fondatrice et PDG',
        'cita1': '"Ma plus grande joie est de voir nos voyageurs découvrir la magie d\'un nouveau lieu"',
        'rol2': 'Spécialiste des destinations asiatiques',
        'cita2': '"Chaque voyage est une histoire et j\'adorerais vous aider à écrire la vôtre."',
        'rol3': 'Coordinateur d\'expériences',
        'cita3': '"Créer des moments inoubliables, une destination à la fois"',
        'rol4': 'Marketing et Communauté',
        'cita4': '"Connecter les voyageurs et partager la passion de l\'exploration."',

        // Información de compra
        'confirmacion_compra': 'Confirmation d\'achat',
        'cargando_confirmacion': 'Chargement des informations de réservation...',
        'volver_inicio': 'Retour à l\'accueil',
        'ver_compra_perfil': 'Voir l\'achat dans le profil',

        // Buscador 
        'limpiar': 'Effacer',
        'filtros': 'Filtres',
        'tipo_viaje': 'Type de voyage',
        'presupuesto_max': 'Budget max',
        'tope': 'Jusqu\'à 2000$',
        'duracion': 'Durée',
        'puntuacion': 'Note',
        'destinos_disponibles': 'Destinations disponibles',

        // Comunidad
        'comunidad_t': 'COMMUNAUTÉ',
        'experiencias_otros': 'Expériences d\'autres utilisateurs',
        'descripcion_experiencia': 'Découvrez les histoires et expériences d\'autres membres de notre communauté. Inspirez-vous et apprenez de leurs parcours.',
        'ver_experiencias': 'Voir les expériences',
        'consejos_otros': 'Conseils d\'autres utilisateurs',
        'descripcion_consejo': 'Trouvez de précieux conseils et astuces partagés par la communauté pour vous aider dans votre propre voyage.',
        'ver_consejos': 'Voir les conseils',
        'deja_consejo': 'Laissez votre propre conseil',
        'descripcion_dejar': 'Votre expérience est précieuse ! Partagez vos connaissances et aidez les autres membres de la communauté.',
        'compartir_consejo': 'Partager un conseil',

        // Seguros 
        'seguro': 'Assurance voyage',
        'pregunta_seguro': 'Souhaitez-vous souscrire une assurance voyage pour 50 € ?',
        'si': 'Oui',
        'no': 'Non',
        'al_seleccionar': 'En la sélectionnant, vous bénéficiez d\'une couverture pour :',
        'c1': 'Assistance médicale et frais d\'hospitalisation (jusqu\'à 50 000 €).',
        'c2': 'Annulation ou interruption de voyage pour cause de force majeure.',
        'c3': 'Perte, vol ou retard de bagages.',
        'c4': 'Rapatriement pour raisons médicales.',
        'poliza1': 'Vous pouvez lire les ',
        'poliza2': 'termes et conditions complets de la police ici',
        'aceptar_seguro': 'J\'accepte les termes et conditions de la police d\'assurance',
        'tyc_poliza': 'Termes et Conditions de la Police d\'Assurance',
        't1': 'Le présent contrat a pour objet de couvrir l\'assuré lors de ses déplacements nationaux et internationaux, contre les risques liés aux accidents, maladies, perte de bagages et autres événements spécifiés dans la police.',
        't2': 'Assuré : Titulaire de la police bénéficiant des garanties souscrites.',
        't5': 'Rapatriement : Entièrement couvert en cas de nécessité médicale.',
        't6': 'Rapatriement : Entièrement couvert en cas de nécessité médicale.',
        't7': 'Cliquez en dehors de la fenêtre pour revenir à la page d\'assurance et accepter les termes de la police.',

        // info compra
        'pack_seleccionado': 'Pack sélectionné',
        'nombre_completo': 'Nom complet',
        'correo_electronico': 'Adresse e-mail',
        'acompanantes': 'Accompagnateurs',
        'viaja_mascotas': 'Voyage avec animaux',
        'tipo_mascota': 'Type d\'animal',
        'intolerancias': 'Intolérances / Allergies',
        'numero_personas': 'Nombre de personnes',
        'seguro_persona': 'Assurance (par personne)',
        'precio_total': 'Prix Total',
        'telefono_emergencia': 'Téléphone d\'urgence',
        'comentarios_adicionales': 'Commentaires supplémentaires',
        'acompanante_singular': 'Accompagnateur',
        'mensaje_exito_compra': 'Votre achat a été confirmé. Voici les détails enregistrés :',
        'mensaje_error_reserva': 'Informations de réservation introuvables. Veuillez réessayer.',
        
        // Perfil
        'perfil_usuario': 'Profil utilisateur',
        'info_perfil': 'Informations du profil',
        'nombre_usuario': 'Nom d\'utilisateur',
        'cerrar_sesion': 'Se déconnecter',
        'cambiar_contrasena': 'Changer le mot de passe',
        'contrasena_actual': 'Mot de passe actuel',
        'contrasena_nueva': 'Nouveau mot de passe',
        'repetir_nueva_contrasena': 'Répéter le nouveau mot de passe',
        'mis_compras': 'Mes achats',
        'mis_consejos': 'Mes conseils',
        'companeros_viaje': 'Compagnons de voyage',
        'destinos_fav': 'Destinations favorites',

        // Perfil Compra (Detalles)
        'detalles_reserva': 'Détails de la réservation',
        'datos_reserva': 'Données de la réservation',
        'deja_reseña': 'Laisser un avis',
        'guardar_reseña': 'Enregistrer l\'avis',
        'ir_inicio': 'Aller à l\'accueil',
        'destinos': 'Destinations',
        // Textes dynamiques de profil
        'fecha': 'Date',
        'precio': 'Prix',
        'ver_detalles': 'Voir détails',
        'eliminar': 'Supprimer',
        'sin_compras': 'Vous n\'avez encore effectué aucun achat.',
        'sin_companeros': 'Vous n\'avez pas de compagnons enregistrés.',
        'sin_favoritos': 'Vous n\'avez pas de destinations favorites enregistrées.',
        'sin_consejos': 'Vous n\'avez publié aucun conseil pour le moment.',
        'estado': 'Statut',
        'confirmada': 'Confirmée'
    }
};

document.addEventListener('DOMContentLoaded', () => {
    // 2. Obtener el selector
    const selector = document.querySelector('.selector-idioma');

    // me aseguro de guardar el idioma entre páginas
    const idiomaGuardado = localStorage.getItem('idioma_seleccionado');

    if (idiomaGuardado) {
        // Ponemos el selector visualmente en el idioma correcto
        if (selector) selector.value = idiomaGuardado; 
        // Traducimos los textos
        cambiarIdioma(idiomaGuardado);
    }
    
    // 3. Escuchar cuando cambias el idioma
    if (selector) {
        selector.addEventListener('change', (event) => {
            const idiomaSeleccionado = event.target.value; // "ES", "EN" o "FR"
            cambiarIdioma(idiomaSeleccionado);

            // guardamos la elección para el futuro
            localStorage.setItem('idioma_seleccionado', idiomaSeleccionado);
        });
    }
});

function cambiarIdioma(idioma) {
    // Busca todos los elementos que tengan el atributo data-lang
    const elementosAtraducir = document.querySelectorAll('[data-lang]');

    elementosAtraducir.forEach(elemento => {
        const clave = elemento.getAttribute('data-lang'); 
        
        // Si existe la traducción, la ponemos
        if (textos[idioma] && textos[idioma][clave]) {
            elemento.textContent = textos[idioma][clave];
        }
    });
}